### ISSUE TITLE
update the readme.md

### ISSUE THREAD

**Issue by Milokita** [cuhk-haosun/nginx-static-file-server#1]
Pls update th README.md with following section:

- how to start & stop the docker
- how to create user with https://github.com/cuhk-haosun/nginx-static-file-server/blob/main/add.user.sh
- how to change the dir of     [    - /home/zx/gluster/nanopore.dna:/srv:ro](https://github.com/cuhk-haosun/nginx-static-file-server/blob/7915d47aeb06a6f3ce15ca097452b32d3d9af3cf/docker-compose.yml#L9C1-L9C46)
- other sections you deem fit

**Comment by fpfcap** [comment]
gotcha
